### ISSUE TITLE
Pass Times Not Returning Early AM passes

### ISSUE THREAD

**Issue by MDStebel** [open-notify/Open-Notify-API#10]
Passes between ~ 11pm and 6am are not being returned out to 50 or more passes.

**Comment by natronics** [comment]
After some digging we decided that that was just true in this one case.

The ISS orbit slowly precesses. Any given pass is going to happen again at _about_ the same time each day, plus or minus an hour. Over the course of weeks or a month, it will slide as the orbit changes to another time of day.

While the user was testing the ISS just happened to be overhead mostly at one time of day.

**Comment by MDStebel** [comment]
Hi Nathan,

The API service for passes seems to be down,
Using a request like this test example below always works, except now returns a can't connect to server error. So, please let me know and thanks!

http://api.open-notify.org/iss-pass.json?lat=29.3&lon=79.0

Michael Stebel
Sent from my iPad



--
Michael Stebel

**Comment by natronics** [comment]
There was an outage early this morning, but it should be resolved now.

**Comment by MDStebel** [comment]
Thanks!

--
Michael Stebel
