### ISSUE TITLE
Endpoints intermittently not working

### ISSUE THREAD

**Issue by jaypeedevlin** [open-notify/Open-Notify-API#11]
Hey Nathan,

Firstly, thanks for maintaining such a cool resource!  We use your api endpoint to teach people how to use APIs.

A few people have reported some patchy performance in the past few days - I was able to get the end points to work every now and then, but much more commonly and getting an '504 Gateway Time-out'.

Not sure if you were aware or not, but want to let you know in case you weren't.

**Comment by aneveu** [comment]
Hey Nathan, 

Thank you for providing those great APIs! 

I have the same issue as Jay, just to let you know too.

**Comment by natronics** [comment]
The server has been under a lot of extra load as of late.

This weekend I tried to add a lot of caching and it seems to have helped. It should be a lot more responsive now!

**Comment by aneveu** [comment]
Thank you Nathan!
