### ISSUE TITLE
iss-now.json is frozen

### ISSUE THREAD

**Issue by iamvdo** [open-notify/Open-Notify-API#14]
This API no longer returns data. Seems frozen...
Thanks !

**Comment by natronics** [comment]
This happened occasionally for brief periods of time. I think I found the reason and patched it.

The updater script has a small memory leak somewhere. Leak might be a strong word, but at any rate left alone too long it crashes for some reason. While I should carefully profile it, I have a cron job to restart it periodically which should fix it.
